name: Add a new Go vulnerability to the database
description: Report a vulnerability that should be added to the Go vulnerability database.
title: "x/vulndb: potential Go vuln in <package>"
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: module
    attributes:
      label: Module
      description: The Go module this vulnerability affects.
      placeholder: https://github.com/example
    validations:
      required: true
  - type: input
    id: package
    attributes:
      label: Package
      description: The Go package this vulnerability affects. Leave blank if same as module.
      placeholder: https://github.com/example/package
    validations:
      required: false
    - type: textarea
      id: description
      attributes:
        label: Description
        description: A description of the vulnerability.
      validations:
        required: true
    - type: textarea
      id: versions
      attributes:
        label: Affected Versions
        description: The package versions affected by this vulnerability.
        value: |
          - Introduced:
          - Fixed:
        render: markdown
      validations:
        required: true
    - type: textarea
      id: symbols
      attributes:
        label: Affected Symbols
        description: The symbols (function or struct names) affected by this vulnerability.
        value: |
          -
          -
        render: markdown
      validations:
        required: true
    - type: dropdown
      id: has-cve
      attributes:
        label: Does this vulnerability already have a CVE ID?
        multiple: false
        options:
        - Has CVE ID
        - Does not have a CVE ID
      validations:
        required: true
    - type: input
      id: cve
      attributes:
        label: CVE ID
        description: The CVE ID for this vulnerability. Leave blank if none exists.
      validations:
        required: false
    - type: input
      id: credit
      attributes:
        label: Credit
        description: [Optional] The name of the person or organization that discovered or fixed this vulnerability.
    - type: textarea
      id: links
      attributes:
        label: References
        description: Links to more information about the vulnerability.
        value: |
          - PR:
          - Commit:
          - Additional Context:
        render: markdown
      validations:
        required: false
    - type: textarea
      id: more
      attributes:
        label: Additional information
        description: Anything else you'd like us to know about this vulnerability?
      validations:
        required: false
